Dev 1.7.0: donate button, optimized mobile experience and more
fi3ework/hexo-theme-archer pull request #399
Opened 2024-05-21 08:17 UTC by LolipopJ

是时候遵循通用 `x.y.z` 版本号规则，让 v1.7.0 来到了（尽管未能全部实现最初规划的功能）。接下来的 Archer 主题发布版本号规则可参考：

- 小型更新和修补递增 `z` 版本号
- 中、大型功能性更新递增 `y` 版本号
- 项目重构与不兼容性更新递增 `x` 版本号。

话不多说，更新的情报请看：

## 新特性 / Feature

- **翻译的文章**：允许配置文章 Front-matter，添加原文章的作者、名称和链接信息。（#265）@Stark-X
- **文章打赏**：支持配置文章打赏信息；支持配置文章 Front-matter，指定文章启用或关闭打赏功能。**目前仅支持桌面端**，移动端的文章打赏功能正在开发中……（#131；参考 h5player for tampermonkey 作者的[文章](https://juejin.cn/post/7341593721100451880)，请对打赏功能的收益做好一定的预期）
- 打开侧边菜单和打赏弹窗时，将相应的按钮置为高亮状态。
- 桌面端：允许通过 ESC 和点击遮盖层的方式关闭 Algolia 搜索弹窗。

## 修复 / Fix

- 移动端：修复点击操作按钮时，悬浮样式保留的问题。（#398）

## 样式 / Style

- 为顶部的 Banner，Algolia 搜索弹窗等位置添加了毛玻璃效果。
- 桌面端：对齐账号信息处的 Icon。（#398）
- 优化多处样式细节。

## 变更 / Change

- 不再随着阅读进度自动设置 URL 的 hash 查询。
- 移动端：不再显示左下角的回到顶部按钮。（#397）
- 去除配置文件中的 `source_version` 字段。应当依靠浏览器的缓存控制策略来加载最新的文件，不再手动进行配置。

## 其它 / Chore

- 迁移 GoogleAnalytics 至 `gtag.js`。@alwaystest
- 替换 `node-sass` 为 `sass`。@Stark-X
- 去除 EJS 模板渲染得到的 HTML 文件里多余的空格。（#374；添加 Hexo 插件 [`hexo-html-minifier`](https://github.com/hexojs/hexo-html-minifier) 或许能更好地解决这个问题）@Stark-X
- 迁移 `waline@1.x` 至 `waline@2.x`。（#386）@Stark-X
- 更新项目依赖，兼容 `node@14.x` 版本；移除 `package-lock.json`。

2024-05-24 05:20 UTC, Stark-X requested changes

2024-05-24 12:13 UTC, LolipopJ commented on .gitignore
> +package-lock.json
锁文件保留与否各有优劣，优势如您述，可以保证构建环境依赖版本的稳定。

去除的话依赖版本按照 `package.json` 的规范控制：

- `"@babel/runtime": "^7.24.5"`：安装最新的 `@babel/runtime@7.x.x` 版本，小于 `8.0.0`；
- `"gulp-postcss": "~9.0.1"`：安装最新的 `gulp-postcss@9.0.x` 版本，小于 `9.1.0`；
- `"anchor-js": "5.0.0"`：安装 `anchor-js@5.0.0` 版本。

尽管有的依赖在 Minor 更新中出现不兼容的情况（例如 `gulp-postcss@9.1.0`），但总体可控。相信社区的力量，保持技术栈的迭代跟进。

对于必须要锁版本的依赖，也可以按照规范之三，去除版本前面的标识符号。

2024-07-20 04:01 UTC, Stark-X approved these changes
LGTM

2024-07-20 06:23 UTC, fi3ework approved these changes

2024-07-20 06:23 UTC, fi3ework commented
👍🏻

2024-07-20 07:15 UTC, merged